### ISSUE TITLE
Npm package

### ISSUE THREAD

**Issue by felixsanz** [rotorz/markdown-it-block-embed#1]
Thanks for creating this fork!

But currently there is a problem with npm install markdown-it-block-embed ... it doesn't work! :stuck_out_tongue_winking_eye:

**Comment by kruncher** [comment]
Hi; yes I am aware of this issue.

I cannot push to npm until I have added the LICENSE file.

I wanted to give the original `markdown-it-video` author the opportunity to review the copyright notice that I need to add to the LICENSE file and at the top of each source file.

For the time being you can install via npm from github:

```
npm install --save https://github.com/rotorz/markdown-it-block-embed.git
```

Apologies for the temporary inconvenience!

Many thanks

**Comment by kruncher** [comment]
Having searched it seems that this is the right thing to do:
http://programmers.stackexchange.com/questions/277688/if-i-fork-a-project-on-github-that-is-licensed-under-mit-how-to-i-handle-the-at

I will follow the guidelines from the above post on StackExchange and push to npm right away.

**Comment by kruncher** [comment]
`npm install --save markdown-it-block-embed` should now be functional!

Please open a new issue if you encounter any issues with this fork!

Thanks again :)
