### ISSUE TITLE
Need env from MarkdownIt.render

### ISSUE THREAD

**Issue by empirefox** [rotorz/markdown-it-block-embed#6]
Sometime i need use runtime env for getVideoUrl from [MarkdownIt.render](https://markdown-it.github.io/markdown-it/#MarkdownIt.render). How can i made this?

**Comment by kruncher** [comment]
Does `this.env.md` get you what you're after?

**Comment by empirefox** [comment]
No. I think i need `_env` of [this line](https://github.com/rotorz/markdown-it-block-embed/blob/master/lib/renderer.js#L7).

**Comment by kruncher** [comment]
What are you wanting to access from `_env`?

**Comment by empirefox** [comment]
I wanted an api_key when rendering. I just resolved this by creating `MarkdownIt` instance after api_key set.

**Comment by kruncher** [comment]
You can provide any extra options you want to your custom service implementation. These can be accessed via `this.options.myCustomOption`.

**Comment by empirefox** [comment]
Yes, i set it via `this.options.myCustomOption` now. Thanks!
